#!/bin/bash

# The initial sentence allows the file to use the bash shell (Thus, the therminal command window)

# Set default input values: the general structure is var_name=${input_numer:-default_value}
density=${1:-0.7}         # Density of particles
Temp=${2:-1.9}            # Bath Temperature of the system
Niter=${3:-4}             # Number of simulations 

# Compile particles.cpp
g++ particles.cpp -o particles_executable

# Create folders for the data
mkdir -p positions
mkdir -p energies

# Loop to save the data
# Here "$" performs a command substitution of "seq", 
# so the different values generated by "seq 1 $Niter" are stored in "i" as the loop runs
for i in $(seq 1 $Niter); do
    
    echo "Iteration $i ..............." # Printing command

    # Run the executable
    ./particles_executable $density $Temp

    # Rename and save the files with "mv" command
    mv position.txt ./positions/position$i.txt
    mv energy.txt ./energies/energy$i.txt

    # Create a file of the last 300 energy data (Here the append operator ">>" is used)
    tail -300 "./energies/energy$i.txt" >> "energies/equilibrium_energies.txt"
    tail -100 "./positions/position$i.txt" >> "positions/equilibrium_positions.txt"
done

# Remove the executables
rm particles_executable

# Text output as help
echo "Execution completed successfully."
echo ""
echo "Variables to add:"
echo "  Density of particles"
echo "  Bath Temperature of the system"
echo "  Number of iterations"
